type Achievement {
  completed: Boolean!
  year: Int
  month: Int
  day: Int
  list: List
}

type List {
  title: String!
  user: User
  achievements: [Achievement] @relation
}

type User {
  email: String!
  lists: [List] @relation
}

type Query {
  findUserByEmail(email: String): User!
}
