const colors = [
  { name: 'AliceBlue', label: 'Alice Blue' },
  { name: 'AntiqueWhite', label: 'Antique White' },
  { name: 'Aqua', label: 'Aqua' },
  { name: 'Aquamarine', label: 'Aquamarine' },
  { name: 'Azure', label: 'Azure' },
  { name: 'Beige', label: 'Beige' },
  { name: 'Bisque', label: 'Bisque' },
  { name: 'Black', label: 'Black' },
  { name: 'BlanchedAlmond', label: 'Blanched Almond' },
  { name: 'Blue', label: 'Blue' },
  { name: 'BlueViolet', label: 'Blue Violet' },
  { name: 'Brown', label: 'Brown' },
  { name: 'BurlyWood', label: 'Burly Wood' },
  { name: 'CadetBlue', label: 'Cadet Blue' },
  { name: 'Chartreuse', label: 'Chartreuse' },
  { name: 'Chocolate', label: 'Chocolate' },
  { name: 'Coral', label: 'Coral' },
  { name: 'CornflowerBlue', label: 'Cornflower Blue' },
  { name: 'Cornsilk', label: 'Cornsilk' },
  { name: 'Crimson', label: 'Crimson' },
  { name: 'Cyan', label: 'Cyan' },
  { name: 'DarkBlue', label: 'DarkBlue' },
  { name: 'DarkCyan', label: 'DarkCyan' },
  { name: 'DarkGoldenRod', label: 'Dark Golden Rod' },
  { name: 'DarkGrey', label: 'Dark Grey' },
  { name: 'DarkGreen', label: 'Dark Green' },
  { name: 'DarkKhaki', label: 'Dark Khaki' },
  { name: 'DarkMagenta', label: 'Dark Magenta' },
  { name: 'DarkOliveGreen', label: 'Dark Olive Green' },
  { name: 'DarkOrange', label: 'Dark Orange' },
  { name: 'DarkOrchid', label: 'Dark Orchid' },
  { name: 'DarkRed', label: 'Dark Red' },
  { name: 'DarkSalmon', label: 'Dark Salmon' },
  { name: 'DarkSeaGreen', label: 'Dark Sea Green' },
  { name: 'DarkSlateBlue', label: 'Dark Slate Blue' },
  { name: 'DarkSlateGrey', label: 'Dark Slate Grey' },
  { name: 'DarkTurquoise', label: 'Dark Turquoise' },
  { name: 'DarkViolet', label: 'Dark Violet' },
  { name: 'DeepPink', label: 'Deep Pink' },
  { name: 'DeepSkyBlue', label: 'Deep Sky Blue' },
  { name: 'DimGrey', label: 'Dim Grey' },
  { name: 'DodgerBlue', label: 'Dodger Blue' },
  { name: 'FireBrick', label: 'Fire Brick' },
  { name: 'FloralWhite', label: 'Floral White' },
  { name: 'ForestGreen', label: 'Forest Green' },
  { name: 'Fuchsia', label: 'Fuchsia' },
  { name: 'Gainsboro', label: 'Gainsboro' },
  { name: 'GhostWhite', label: 'Ghost White' },
  { name: 'Gold', label: 'Gold' },
  { name: 'GoldenRod', label: 'Golden Rod' },
  { name: 'Grey', label: 'Grey' },
  { name: 'Green', label: 'Green' },
  { name: 'GreenYellow', label: 'Green Yellow' },
  { name: 'HoneyDew', label: 'Honey Dew' },
  { name: 'HotPink', label: 'Hot Pink' },
  { name: 'IndianRed', label: 'Indian Red' },
  { name: 'Indigo', label: 'Indigo' },
  { name: 'Ivory', label: 'Ivory' },
  { name: 'Khaki', label: 'Khaki' },
  { name: 'Lavender', label: 'Lavender' },
  { name: 'LavenderBlush', label: 'Lavender Blush' },
  { name: 'LawnGreen', label: 'Lawn Green' },
  { name: 'LemonChiffon', label: 'Lemon Chiffon' },
  { name: 'LightBlue', label: 'Light Blue' },
  { name: 'LightCoral', label: 'Light Coral' },
  { name: 'LightCyan', label: 'Light Cyan' },
  { name: 'LightGoldenRodYellow', label: 'Light Golden Rod Yellow' },
  { name: 'LightGrey', label: 'Light Grey' },
  { name: 'LightGreen', label: 'Light Green' },
  { name: 'LightPink', label: 'Light Pink' },
  { name: 'LightSalmon', label: 'Light Salmon' },
  { name: 'LightSeaGreen', label: 'Light Sea Green' },
  { name: 'LightSkyBlue', label: 'Light Sky Blue' },
  { name: 'LightSlateGrey', label: 'Light Slate Grey' },
  { name: 'LightSteelBlue', label: 'Light Steel Blue' },
  { name: 'LightYellow', label: 'Light Yellow' },
  { name: 'Lime', label: 'Lime' },
  { name: 'LimeGreen', label: 'Lime Green' },
  { name: 'Linen', label: 'Linen' },
  { name: 'Magenta', label: 'Magenta' },
  { name: 'Maroon', label: 'Maroon' },
  { name: 'MediumAquaMarine', label: 'Medium Aqua Marine' },
  { name: 'MediumBlue', label: 'Medium Blue' },
  { name: 'MediumOrchid', label: 'Medium Orchid' },
  { name: 'MediumPurple', label: 'Medium Purple' },
  { name: 'MediumSeaGreen', label: 'Medium Sea Green' },
  { name: 'MediumSlateBlue', label: 'Medium Slate Blue' },
  { name: 'MediumSpringGreen', label: 'Medium Spring Green' },
  { name: 'MediumTurquoise', label: 'Medium Turquoise' },
  { name: 'MediumVioletRed', label: 'Medium Violet Red' },
  { name: 'MidnightBlue', label: 'Midnight Blue' },
  { name: 'MintCream', label: 'Mint Cream' },
  { name: 'MistyRose', label: 'Misty Rose' },
  { name: 'Moccasin', label: 'Moccasin' },
  { name: 'NavajoWhite', label: 'Navajo White' },
  { name: 'Navy', label: 'Navy' },
  { name: 'OldLace', label: 'OldLace' },
  { name: 'Olive', label: 'Olive' },
  { name: 'OliveDrab', label: 'Olive Drab' },
  { name: 'Orange', label: 'Orange' },
  { name: 'OrangeRed', label: 'Orange Red' },
  { name: 'Orchid', label: 'Orchid' },
  { name: 'PaleGoldenRod', label: 'Pale Golden Rod' },
  { name: 'PaleGreen', label: 'Pale Green' },
  { name: 'PaleTurquoise', label: 'Pale Turquoise' },
  { name: 'PaleVioletRed', label: 'Pale Violet Red' },
  { name: 'PapayaWhip', label: 'Papaya Whip' },
  { name: 'PeachPuff', label: 'Peach Puff' },
  { name: 'Peru', label: 'Peru' },
  { name: 'Pink', label: 'Pink' },
  { name: 'Plum', label: 'Plum' },
  { name: 'PowderBlue', label: 'Powder Blue' },
  { name: 'Purple', label: 'Purple' },
  { name: 'RebeccaPurple', label: 'Rebecca Purple' },
  { name: 'Red', label: 'Red' },
  { name: 'RosyBrown', label: 'Rosy Brown' },
  { name: 'RoyalBlue', label: 'Royal Blue' },
  { name: 'SaddleBrown', label: 'Saddle Brown' },
  { name: 'Salmon', label: 'Salmon' },
  { name: 'SandyBrown', label: 'Sandy Brown' },
  { name: 'SeaGreen', label: 'Sea Green' },
  { name: 'SeaShell', label: 'Sea Shell' },
  { name: 'Sienna', label: 'Sienna' },
  { name: 'Silver', label: 'Silver' },
  { name: 'SkyBlue', label: 'SkyBlue' },
  { name: 'SlateBlue', label: 'Slate Blue' },
  { name: 'SlateGrey', label: 'Slate Grey' },
  { name: 'Snow', label: 'Snow' },
  { name: 'SpringGreen', label: 'Spring Green' },
  { name: 'SteelBlue', label: 'Steel Blue' },
  { name: 'Tan', label: 'Tan' },
  { name: 'Teal', label: 'Teal' },
  { name: 'Thistle', label: 'Thistle' },
  { name: 'Tomato', label: 'Tomato' },
  { name: 'Turquoise', label: 'Turquoise' },
  { name: 'Violet', label: 'Violet' },
  { name: 'Wheat', label: 'Wheat' },
  { name: 'White', label: 'White' },
  { name: 'WhiteSmoke', label: 'White Smoke' },
  { name: 'Yellow', label: 'Yellow' },
  { name: 'YellowGreen', label: 'Yellow Green' },
];

export { colors };
